### ISSUE TITLE
minified files should be loaded normally; unminified in debug mode

### ISSUE THREAD

**Issue by jeffreykemp** [vincentmorneau/animapex#6]
.min files are being loaded only in debug mode, which is the opposite of what I'd expect. This is due to a missing "else" in the following code:

	-- debug
	if apex_application.g_debug then
		apex_plugin_util.debug_dynamic_action (
			p_plugin => p_plugin
			, p_dynamic_action => p_dynamic_action
		);
	else <-------
		l_min := '.min';
	end if;

**Comment by vincentmorneau** [comment]
Ha! Good catch. Thanks.

**Comment by Dani3lSun** [comment]
Since APEX 5.0 you can use the *File URLs to Load* attribute. In there you can use the #MIN# substitution. So only in debug mode the un-minified versions are deployed...
If you do this you can remove all plugin file calls in your PL/SQL code, like *apex_javascript.add_library* and *apex_css.add_file*
<img width="520" alt="screen shot 2017-10-31 at 14 48 22" src="https://user-images.githubusercontent.com/698942/32227224-15a60ea2-be4b-11e7-89f6-284e68dd025b.png">
The help text of this attribute explains some common settings...

**Comment by vincentmorneau** [comment]
@Dani3lSun good point. Any reason why you use the apex_javascript and apex_css APIs on this one: https://github.com/Dani3lSun/apex-plugin-apextooltip/blob/master/source/render_dynamicaction.sql ?

I based the implementation of AnimAPEX on this plugin of yours 😃

**Comment by Dani3lSun** [comment]
@vincentmorneau I know :) That´s basically a historical issue, you know things better after you do it for a longer period :)
A lot of my early plugins are based on my knowledge I got with 4.x, so in early 5.0 times I used this "old" method...But to be honest, both methods are fine, but the newer "File URLs to Load" attribute makes it more simple to use, thus you have no if-then-else logic + add_file calls in your PL/SQL code...
If you want to conditionally load a file or not, then you have to use the PL/SQL API for that...

**Comment by vincentmorneau** [comment]
Makes sense. I prefer the File URLs to Load to I'll update with that.
